import React, { useEffect, useRef, useState } from 'react';
import { Link, Navigate, useLocation, useNavigate, useSearchParams } from 'react-router-dom';
import { api, money } from './api';
import { useStore, useLoad, Icon, Photo, ProductCard, Empty, Loading, ErrorBox } from './shared';
export function Auth() {
  const signup = useLocation().pathname === '/signup', { user, setUser, refresh, catalog, notify } = useStore(), navigate = useNavigate(), location = useLocation(), [error, setError] = useState(''), [busy, setBusy] = useState(false);
  const from = location.state?.from?.startsWith('/') && !location.state.from.startsWith('//') ? location.state.from : '/profile';
  if (user) return <Navigate to={from} replace/>;
  return <main className="auth-layout"><div className="auth-art"><Photo src={catalog.maincategory.find(c => c.name === 'Female')?.pic} alt="Personal style at Apna Bazar"/><div><span className="eyebrow">YOUR STYLE. YOUR SPACE.</span><h2>Good to<br/>have you here.</h2><p>A world of everyday favourites awaits.</p></div></div><div className="auth-form"><span className="eyebrow">MAKE YOURSELF AT HOME</span><h1>{signup ? 'A fresh beginning.' : 'Welcome back.'}</h1><p>{signup ? 'Create an account to save, shop and find your favourites.' : 'Sign in for a little more you.'}</p><form onSubmit={async e => { e.preventDefault(); setBusy(true); setError(''); const values = Object.fromEntries(new FormData(e.currentTarget)); try { const u = await api(`/auth/${signup ? 'signup' : 'login'}`, { method: 'POST', body: values }); setUser(u); navigate(from, { replace: true }); refresh().catch(err => notify(err.message)); } catch (e) { setError(e.message); } finally { setBusy(false); } }}>{signup && <label>Your name<input name="name" autoComplete="name" minLength={2} required placeholder="First and last name"/></label>}<label>Email address<input type="email" name="email" autoComplete="email" required placeholder="you@example.com"/></label><label>Password<input type="password" name="password" autoComplete={signup ? 'new-password' : 'current-password'} minLength={signup ? 8 : undefined} required placeholder={signup ? 'At least 8 characters' : 'Your password'}/></label><ErrorBox error={error}/><button className="btn full" disabled={busy}>{busy ? 'One moment…' : signup ? 'Create your account' : 'Sign in'}<Icon name="arrow"/></button></form><p className="auth-switch">{signup ? 'Already part of the community?' : 'New around here?'} <Link to={signup ? '/login' : '/signup'} state={location.state}>{signup ? 'Sign in' : 'Join us'}</Link></p><Link className="underlined" to="/shop">A little browsing first<Icon name="arrow" size={16}/></Link></div></main>;
}
function OrderSummary({ checkout = false }) { const { cart } = useStore(); return <aside className="order-summary"><span className="eyebrow">THE GOOD PART</span><h2>Your order summary</h2><div><span>Subtotal</span><span>{money(cart.subtotal)}</span></div><div><span>Delivery</span><span>{cart.shipping ? money(cart.shipping) : 'On us'}</span></div><div className="summary-total"><span>Total</span><span>{money(cart.total)}</span></div><small>Inclusive of all taxes</small>{cart.subtotal < 1999 && <p className="shipping-note">You’re {money(1999 - cart.subtotal)} away from complimentary delivery.</p>}{!checkout && <Link className="btn full" to="/checkout">Continue to checkout<Icon name="arrow"/></Link>}<p className="secure-note"><Icon name="shield" size={16}/>Secure checkout · Pay on delivery</p></aside>; }
export function Cart() {
  const { cart, setCart, notify, refresh } = useStore(), [busy, setBusy] = useState('');
  useEffect(() => { refresh().catch(e => notify(e.message)); }, [refresh, notify]);
  async function change(id, qty) { setBusy(id); try { setCart(await api(`/cart/${id}`, { method: qty === 0 ? 'DELETE' : 'PATCH', body: qty ? { qty } : undefined })); } catch (e) { notify(e.message); } finally { setBusy(''); } }
  return <main className="page"><div className="page-heading"><span className="eyebrow">ALL YOUR GOOD FINDS</span><h1>Your shopping bag<span className="heading-count">({cart.items.length})</span></h1></div>{!cart.items.length ? <Empty title="A little room for something lovely." text="Your bag is empty. Let’s find something that feels like you."/> : <div className="checkout-layout"><div className="cart-items">{cart.items.map(i => <article className="cart-item" key={i.id}><Link to={`/product/${i.product}`}><Photo src={i.pic} alt={i.name}/></Link><div><Link to={`/product/${i.product}`}><h3>{i.name}</h3></Link><p>Size {i.size}</p><strong>{money(i.price)}</strong>{(!i.available || i.qty > i.stockQuantity) && <p className="error">Please adjust or remove this item. Available: {i.stockQuantity}</p>}<div className="quantity"><button disabled={i.qty <= 1 || !!busy} onClick={() => change(i.id, i.qty - 1)} aria-label={`Decrease ${i.name}`}>−</button><span>{i.qty}</span><button disabled={i.qty >= Math.min(i.stockQuantity, 20) || !!busy} onClick={() => change(i.id, i.qty + 1)} aria-label={`Increase ${i.name}`}>+</button></div></div><div className="cart-item-end"><strong>{money(i.total)}</strong><button className="icon-button" disabled={!!busy} onClick={() => change(i.id, 0)} aria-label={`Remove ${i.name}`}><Icon name="trash" size={18}/></button></div></article>)}<Link className="underlined" to="/shop">A little more browsing<Icon name="arrow" size={18}/></Link></div><OrderSummary/></div>}</main>;
}
const addressFields = [['name','Full name'],['phone','Phone number'],['address','Street address'],['city','City'],['state','State'],['pin','PIN code']];
function ProfilePhoto() {
  const { user, setUser, notify } = useStore(), [busy, setBusy] = useState(false);
  return <div className="profile-avatar"><Photo src={user.pic} alt="Your profile photo"/><label>{busy ? 'Uploading…' : 'Change profile photo'}<input aria-label="Upload profile photo" type="file" accept="image/jpeg,image/png,image/webp,image/avif" disabled={busy} onChange={async e => { const file = e.target.files[0]; if (!file) return; if (file.size > 5 * 1024 * 1024) return notify('Please choose an image under 5 MB.'); setBusy(true); try { const body = new FormData(); body.append('image', file); setUser(await api('/auth/avatar', { method: 'POST', body })); notify('Profile photo updated.'); } catch (e) { notify(e.message); } finally { setBusy(false); } }}/><small>JPEG, PNG, WebP or AVIF · up to 5 MB</small></label></div>;
}
export function AddressFields({ user }) { return <div className="form-grid">{addressFields.map(([key, label]) => <label className={key === 'address' ? 'span-two' : ''} key={key}>{label}<input name={key} defaultValue={user?.[key] || ''} required maxLength={200} pattern={key === 'pin' ? '[0-9]{6}' : undefined} minLength={key === 'phone' ? 10 : undefined} inputMode={['pin','phone'].includes(key) ? 'numeric' : undefined} autoComplete={{ name: 'name', phone: 'tel', address: 'street-address', city: 'address-level2', state: 'address-level1', pin: 'postal-code' }[key]}/></label>)}</div>; }
export function Checkout() {
  const { user, cart, refresh } = useStore(), [busy, setBusy] = useState(false), [error, setError] = useState(''), navigate = useNavigate(), key = useRef(crypto.randomUUID());
  if (!cart.items.length) return <main className="page"><Empty title="Your bag is waiting." text="Add a favourite before checking out."/></main>;
  return <main className="page"><div className="page-heading"><span className="eyebrow">ONE STEP CLOSER TO YOUR FAVOURITES</span><h1>Make it yours.</h1></div><div className="checkout-layout"><form onSubmit={async e => { e.preventDefault(); setBusy(true); setError(''); const address = Object.fromEntries(new FormData(e.currentTarget)); try { const order = await api('/orders', { method: 'POST', headers: { 'Idempotency-Key': key.current }, body: { address, paymentMode: 'cod' } }); await refresh(); navigate(`/order-confirmation?id=${order.id}`); } catch (e) { setError(e.message); } finally { setBusy(false); } }}><div className="form-panel"><h2><span className="step-number">01</span>Where should we send it?</h2><AddressFields user={user}/></div><div className="form-panel"><h2><span className="step-number">02</span>A simple way to pay</h2><label className="payment-choice"><input type="radio" name="payment" defaultChecked/><span><strong>Cash on delivery</strong><small>Pay when your order arrives. No advance payment.</small></span><Icon name="shield"/></label></div><ErrorBox error={error}/><button className="btn full" disabled={busy || cart.items.some(i => i.qty > i.stockQuantity || !i.available)}>{busy ? 'Placing your order…' : `Place order · ${money(cart.total)}`}<Icon name="arrow"/></button></form><div><OrderSummary checkout/><div className="checkout-preview">{cart.items.map(i => <div key={i.id}><Photo src={i.pic} alt={i.name}/><span>{i.name}<small>Size {i.size} · Qty {i.qty}</small></span><strong>{money(i.total)}</strong></div>)}</div></div></div></main>;
}
export function Confirmation() { const [params] = useSearchParams(), { data, loading, error } = useLoad('/orders'); if (loading) return <Loading/>; const order = data?.find(o => o.id === params.get('id')); return <main className="page confirmation"><ErrorBox error={error}/>{order ? <><span className="success-check"><Icon name="check" size={36}/></span><span className="eyebrow">A VERY GOOD CHOICE</span><h1>It’s officially yours.</h1><p>Your order has been placed. We’ll take it from here.</p><div className="confirmation-details"><span>Order #{order.id.slice(0, 8).toUpperCase()}</span><strong>{money(order.total)}</strong><span>Cash on delivery · Payment pending</span><span>{order.address.name} · {order.address.city}, {order.address.pin}</span></div><Link className="btn" to="/profile?tab=orders">View your orders<Icon name="arrow"/></Link><Link className="underlined" to="/shop">Keep exploring</Link></> : <Empty title="Order not found" text="You can find your purchases in your account." link="/profile?tab=orders" action="Your orders"/>}</main>; }
export function Wishlist() { const { wishlist } = useStore(); return <main className="page"><div className="page-heading"><span className="eyebrow">KEEP THE GOOD ONES CLOSE</span><h1>Saved for a little later.</h1><p>Your personal edit of favourites.</p></div>{wishlist.length ? <div className="product-grid">{wishlist.map(p => <ProductCard key={p.id} product={p}/>)}</div> : <Empty title="A place for your favourites." text="Tap the heart on any piece to save it here."/>}</main>; }
export function Account() {
  const { user, setUser, setCart, setWishlist, refresh, notify } = useStore(), [params, setParams] = useSearchParams(), tab = params.get('tab') || 'profile', { data: orders, error, loading, reload } = useLoad('/orders'), [busy, setBusy] = useState(false), navigate = useNavigate();
  return <main className="page"><div className="page-heading"><span className="eyebrow">YOUR LITTLE CORNER</span><h1>Hello, {user.name.split(' ')[0]}.</h1><p>All your favourites, in one place.</p></div><div className="account-layout"><aside className="account-nav"><button className={tab === 'profile' ? 'active' : ''} onClick={() => setParams({ tab: 'profile' })}>Personal details<Icon name="user" size={18}/></button><button className={tab === 'orders' ? 'active' : ''} onClick={() => setParams({ tab: 'orders' })}>My orders<Icon name="bag" size={18}/></button><Link to="/wishlist">Saved favourites<Icon name="heart" size={18}/></Link>{['Admin', 'Super Admin'].includes(user.role) && <Link to="/admin">Store management<Icon name="arrow" size={18}/></Link>}<button disabled={busy} onClick={async () => { setBusy(true); try { await api('/auth/logout', { method: 'POST' }); setUser(null); setCart({ items: [], subtotal: 0, shipping: 0, total: 0 }); setWishlist([]); window.location.replace('/'); } catch (e) { notify(e.message); setBusy(false); } }}>Sign out</button></aside><div>{tab === 'profile' ? <form className="form-panel" onSubmit={async e => { e.preventDefault(); setBusy(true); try { setUser(await api('/auth/me', { method: 'PATCH', body: Object.fromEntries(new FormData(e.currentTarget)) })); await refresh(); notify('Your details have been saved.'); } catch (e) { notify(e.message); } finally { setBusy(false); } }}><ProfilePhoto/><h2>Your details & delivery address</h2><p className="muted">{user.email}</p><AddressFields user={user}/><button className="btn" disabled={busy}>{busy ? 'Saving…' : 'Save your details'}<Icon name="check" size={18}/></button></form> : <><h2>Your orders</h2><ErrorBox error={error} retry={reload}/>{loading ? <Loading/> : orders?.length ? orders.map(o => <article className="order-card" key={o.id}><div className="order-top"><div><strong>Order #{o.id.slice(0, 8).toUpperCase()}</strong><small>{new Date(o.createdAt).toLocaleDateString('en-IN', { dateStyle: 'long' })}</small></div><span className="status-badge">{o.status}</span><strong>{money(o.total)}</strong></div>{o.items?.map((i, n) => <div className="order-line" key={n}><Photo src={i.pic} alt={i.name}/><span>{i.name}<small>Qty {i.qty} · Size {i.size}</small></span></div>)}<div className="order-bottom">{o.paymentMode === 'cod' ? 'Cash on delivery' : o.paymentMode} · {o.paymentStatus}<span>{o.address?.city}, {o.address?.pin}</span></div></article>) : <Empty title="Your story is just beginning." text="Your orders will appear right here."/>}</>}</div></div></main>;
}
